"""create initial schema

Revision ID: 4a097ff7fccb
Revises:
Create Date: 2026-09-21 23:57:55.917192
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4a097ff7fccb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_rate_limits",
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column("window_start", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_auth_rate_limits_attempts_nonnegative")),
        sa.PrimaryKeyConstraint(
            "scope", "key_hash", "window_start", name=op.f("pk_auth_rate_limits")
        ),
        sqlite_strict=True,
    )
    op.create_index("ix_auth_rate_limits_expiry", "auth_rate_limits", ["expires_at"], unique=False)
    op.create_table(
        "cities",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("parent_name", sa.Text(), nullable=True),
        sa.Column("unit_kind", sa.Text(), nullable=False),
        sa.Column("mapping_status", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "mapping_status IN ('pending', 'verified')", name=op.f("ck_cities_mapping_status")
        ),
        sa.CheckConstraint("is_active IN (0, 1)", name=op.f("ck_cities_active_flag")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cities")),
        sa.UniqueConstraint("provider", "provider_code", name=op.f("uq_cities_provider")),
        sqlite_strict=True,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("username_key", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username_key", name=op.f("uq_users_username_key")),
        sqlite_strict=True,
    )
    op.create_table(
        "albums",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("city_id", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_albums_revision_positive")),
        sa.CheckConstraint(
            "year IS NULL OR year BETWEEN 1 AND 9999", name=op.f("ck_albums_valid_year")
        ),
        sa.ForeignKeyConstraint(
            ["city_id"], ["cities.id"], name=op.f("fk_albums_city_id_cities"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_albums_owner_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_albums")),
        sa.UniqueConstraint("id", "owner_id", name=op.f("uq_albums_id")),
        sqlite_strict=True,
    )
    op.create_index(
        "uq_albums_unmarked",
        "albums",
        ["owner_id", "city_id"],
        unique=True,
        sqlite_where=sa.text("year IS NULL"),
    )
    op.create_index(
        "uq_albums_year",
        "albums",
        ["owner_id", "city_id", "year"],
        unique=True,
        sqlite_where=sa.text("year IS NOT NULL"),
    )
    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("csrf_token", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.Integer(), nullable=False),
        sa.Column("revoked_at", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_sessions_expiry_after_creation")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_sessions")),
        sqlite_strict=True,
    )
    op.create_index("ix_sessions_expiry", "sessions", ["expires_at"], unique=False)
    op.create_index("ix_sessions_user", "sessions", ["user_id"], unique=False)
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("album_id", sa.Text(), nullable=False),
        sa.Column("request_key", sa.Text(), nullable=False),
        sa.Column("request_hash", sa.Text(), nullable=False),
        sa.Column("expected_count", sa.Integer(), nullable=False),
        sa.Column("state", sa.Text(), server_default="open", nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.Column("committed_at", sa.Integer(), nullable=True),
        sa.Column("commit_request_hash", sa.Text(), nullable=True),
        sa.Column("commit_result_json", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(state = 'committed' AND committed_at IS NOT NULL AND commit_request_hash IS NOT NULL AND commit_result_json IS NOT NULL) OR (state <> 'committed' AND committed_at IS NULL AND commit_request_hash IS NULL AND commit_result_json IS NULL)",
            name=op.f("ck_import_batches_commit_receipt_matches_state"),
        ),
        sa.CheckConstraint(
            "state IN ('open', 'committed', 'canceled', 'expired')",
            name=op.f("ck_import_batches_valid_state"),
        ),
        sa.CheckConstraint(
            "expected_count > 0", name=op.f("ck_import_batches_expected_count_positive")
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_import_batches_expiry_after_creation")
        ),
        sa.CheckConstraint(
            "length(request_hash) = 64", name=op.f("ck_import_batches_request_hash_length")
        ),
        sa.ForeignKeyConstraint(
            ["album_id", "owner_id"],
            ["albums.id", "albums.owner_id"],
            name=op.f("fk_import_batches_album_id_albums"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
        sa.UniqueConstraint("id", "owner_id", name=op.f("uq_import_batches_id")),
        sa.UniqueConstraint("owner_id", "request_key", name=op.f("uq_import_batches_owner_id")),
        sqlite_strict=True,
    )
    op.create_index(
        "ix_import_batches_album", "import_batches", ["album_id", "owner_id"], unique=False
    )
    op.create_index(
        "ix_import_batches_expiry", "import_batches", ["state", "expires_at"], unique=False
    )
    op.create_table(
        "upload_items",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("batch_id", sa.Text(), nullable=False),
        sa.Column("item_index", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("expected_bytes", sa.Integer(), nullable=False),
        sa.Column("expected_sha256", sa.Text(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("reserved_photo_id", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), server_default="pending", nullable=False),
        sa.Column("attempt_token", sa.Text(), nullable=True),
        sa.Column("lease_until", sa.Integer(), nullable=True),
        sa.Column("actual_bytes", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.Text(), nullable=True),
        sa.Column("mime_type", sa.Text(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("failure_code", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(state = 'receiving' AND attempt_token IS NOT NULL AND lease_until IS NOT NULL) OR (state <> 'receiving' AND attempt_token IS NULL AND lease_until IS NULL)",
            name=op.f("ck_upload_items_receiving_has_lease"),
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'receiving', 'staged', 'failed', 'committed', 'discarded')",
            name=op.f("ck_upload_items_valid_state"),
        ),
        sa.CheckConstraint(
            "state NOT IN ('staged', 'committed') OR (actual_bytes IS NOT NULL AND actual_bytes = expected_bytes AND sha256 IS NOT NULL AND sha256 = expected_sha256 AND mime_type IS NOT NULL AND mime_type IN ('image/jpeg', 'image/png', 'image/webp') AND width IS NOT NULL AND width > 0 AND height IS NOT NULL AND height > 0)",
            name=op.f("ck_upload_items_staged_file_metadata_complete"),
        ),
        sa.CheckConstraint(
            "expected_bytes > 0", name=op.f("ck_upload_items_expected_bytes_positive")
        ),
        sa.CheckConstraint("item_index >= 0", name=op.f("ck_upload_items_item_index_nonnegative")),
        sa.CheckConstraint(
            "length(expected_sha256) = 64", name=op.f("ck_upload_items_expected_hash_length")
        ),
        sa.ForeignKeyConstraint(
            ["batch_id", "owner_id"],
            ["import_batches.id", "import_batches.owner_id"],
            name=op.f("fk_upload_items_batch_id_import_batches"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upload_items")),
        sa.UniqueConstraint("batch_id", "item_index", name=op.f("uq_upload_items_batch_id")),
        sa.UniqueConstraint("id", "owner_id", name=op.f("uq_upload_items_id")),
        sa.UniqueConstraint("reserved_photo_id", name=op.f("uq_upload_items_reserved_photo_id")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_upload_items_storage_key")),
        sqlite_strict=True,
    )
    op.create_table(
        "photos",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("album_id", sa.Text(), nullable=False),
        sa.Column("upload_item_id", sa.Text(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), server_default="", nullable=False),
        sa.Column("state", sa.Text(), server_default="active", nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.Integer(), nullable=True),
        sa.Column("purge_after", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(state = 'active' AND position IS NOT NULL AND position >= 0 AND deleted_at IS NULL AND purge_after IS NULL) OR (state IN ('trashed', 'purging') AND position IS NULL AND deleted_at IS NOT NULL AND purge_after IS NOT NULL AND purge_after = deleted_at + 2592000000)",
            name=op.f("ck_photos_lifecycle_fields_match_state"),
        ),
        sa.CheckConstraint(
            "mime_type IN ('image/jpeg', 'image/png', 'image/webp')",
            name=op.f("ck_photos_valid_mime_type"),
        ),
        sa.CheckConstraint(
            "state IN ('active', 'trashed', 'purging')", name=op.f("ck_photos_valid_state")
        ),
        sa.CheckConstraint("byte_size > 0", name=op.f("ck_photos_byte_size_positive")),
        sa.CheckConstraint("height > 0", name=op.f("ck_photos_height_positive")),
        sa.CheckConstraint("length(note) <= 2000", name=op.f("ck_photos_note_length")),
        sa.CheckConstraint("length(sha256) = 64", name=op.f("ck_photos_hash_length")),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_photos_revision_positive")),
        sa.CheckConstraint("width > 0", name=op.f("ck_photos_width_positive")),
        sa.ForeignKeyConstraint(
            ["album_id", "owner_id"],
            ["albums.id", "albums.owner_id"],
            name=op.f("fk_photos_album_id_albums"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["upload_item_id", "owner_id"],
            ["upload_items.id", "upload_items.owner_id"],
            name=op.f("fk_photos_upload_item_id_upload_items"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_photos")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_photos_storage_key")),
        sa.UniqueConstraint("upload_item_id", name=op.f("uq_photos_upload_item_id")),
        sqlite_strict=True,
    )
    op.create_index(
        "ix_photos_duplicate_hint",
        "photos",
        ["owner_id", "album_id", "sha256"],
        unique=False,
        sqlite_where=sa.text("state = 'active'"),
    )
    op.create_index("ix_photos_purge", "photos", ["state", "purge_after"], unique=False)
    op.create_index("ix_photos_trash", "photos", ["owner_id", "state", "deleted_at"], unique=False)
    op.create_index(
        "uq_photos_active_position",
        "photos",
        ["album_id", "position"],
        unique=True,
        sqlite_where=sa.text("state = 'active'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_photos_active_position", table_name="photos", sqlite_where=sa.text("state = 'active'")
    )
    op.drop_index("ix_photos_trash", table_name="photos")
    op.drop_index("ix_photos_purge", table_name="photos")
    op.drop_index(
        "ix_photos_duplicate_hint", table_name="photos", sqlite_where=sa.text("state = 'active'")
    )
    op.drop_table("photos")
    op.drop_table("upload_items")
    op.drop_index("ix_import_batches_expiry", table_name="import_batches")
    op.drop_index("ix_import_batches_album", table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index("ix_sessions_user", table_name="sessions")
    op.drop_index("ix_sessions_expiry", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("uq_albums_year", table_name="albums", sqlite_where=sa.text("year IS NOT NULL"))
    op.drop_index("uq_albums_unmarked", table_name="albums", sqlite_where=sa.text("year IS NULL"))
    op.drop_table("albums")
    op.drop_table("users")
    op.drop_table("cities")
    op.drop_index("ix_auth_rate_limits_expiry", table_name="auth_rate_limits")
    op.drop_table("auth_rate_limits")
    # ### end Alembic commands ###
